### PR TITLE
Initial

### PR DESCRIPTION
**Pull request by njuettner**
Issue: https://github.com/giantswarm/roadmap/issues/2180

By running `VERSION=v1.13.0 hack/sync.sh` it will copy the upstream Cilium network policies CRDs into templates.

### CODE REVIEW

**Review by T-Kukawka — APPROVED** [review]

**Comment by whites11** [comment]
I don't think we can do like this.
Having the CRDs defined as an helm template object means that when we'll delete the app the CRDs will be deleted, and the CRs as well.
Cilium will probably recreate the CRDs, but the CRs will be lost.
I think we should have a pod `kubectl apply` them as an helm chart, instead

**Comment by whites11** [comment]
as a possible reference/idea https://github.com/giantswarm/cilium-app/blob/main/helm/cilium/templates/default-policies/job.yaml

**Comment by njuettner** [comment]
@whites11 Yeah good point, I was not really sure about that, wanted to test it.
But I think your approach is better. CRD's are now applied via `kubectl apply`.

I tested it manually, CRDs are still present once I deleted the helm chart.

**Review by whites11 — APPROVED** [review]
looks good

**Pull request merged**
